"""empty message

Revision ID: 456f27ee36a5
Revises: 
Create Date: 2025-10-08 16:39:50.450124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456f27ee36a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('questao_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questao_fk'], ['questao.id'], name='fk_opcao_questao'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questao_fk', sa.Integer(), nullable=True),
    sa.Column('opcao_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opcao_fk'], ['opcao.id'], name='fk_resposta_opcao'),
    sa.ForeignKeyConstraint(['questao_fk'], ['questao.id'], name='fk_resposta_questao'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    op.drop_table('opcao')
    op.drop_table('questao')
    # ### end Alembic commands ###
